import React from 'react';
import {useNavigate} from "react-router-dom";
import {LOGIN_PATH} from "../../routes/Slug.js";
import PrimaryBtn from "../buttons/PrimaryBtn.jsx";
import ImageView from "../viewer/ImageView.jsx";
import GoBackBtn from "../buttons/GoBackBtn.jsx";

import "./admin_login_done_content.scss";

const AdminLoginDoneContent = () => {

    const navigate = useNavigate();

    return (
        <div className="admin-activation-done-content">
            <GoBackBtn
                onClick={() => navigate(-1)}
            />

            <div className="admin-activation-done-content-wrapper">
                <ImageView
                    url="/assets/icons/check_circle.svg"
                    style={{width: "120px", height: "120px", margin: "0 auto"}}
                />
                <p className="admin-activation-done-content-title">
                    Congratulations! Your admin account has been activated.
                </p>
                <p>
                    To log in in the future, you will need to enter your User ID and the
                    authentication code generated by your authenticator app.
                </p>
                <p>
                    Make sure to keep your authenticator app installed on your device to
                    access the system securely.
                </p>
                <PrimaryBtn
                    type="primary"
                    style={{width: "100%", marginTop: "16px"}}
                    onClick={() => navigate(LOGIN_PATH)}
                    btnName="Proceed to Login"
                />
            </div>

        </div>
    );
};

export default AdminLoginDoneContent;